//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18033
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowPad.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowPad.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextConnect {
            get {
                return ResourceManager.GetString("AppBarButtonTextConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextDelete {
            get {
                return ResourceManager.GetString("AppBarButtonTextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextDisconnect {
            get {
                return ResourceManager.GetString("AppBarButtonTextDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextMouse {
            get {
                return ResourceManager.GetString("AppBarButtonTextMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wake On Lan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextPower {
            get {
                return ResourceManager.GetString("AppBarButtonTextPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextSearchPC {
            get {
                return ResourceManager.GetString("AppBarButtonTextSearchPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextSettings {
            get {
                return ResourceManager.GetString("AppBarButtonTextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch Screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarButtonTextTouchScreen {
            get {
                return ResourceManager.GetString("AppBarButtonTextTouchScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact us과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarMenuTextEmail {
            get {
                return ResourceManager.GetString("AppBarMenuTextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarMenuTextHelp {
            get {
                return ResourceManager.GetString("AppBarMenuTextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rate &amp; Review과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppBarMenuTextRateNReview {
            get {
                return ResourceManager.GetString("AppBarMenuTextRateNReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velostep WowPad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppFullName {
            get {
                return ResourceManager.GetString("AppFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access code is incorrect. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageAccessCodeIncorrect {
            get {
                return ResourceManager.GetString("AppMessageAccessCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy the MK version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageBuyMKVersion {
            get {
                return ResourceManager.GetString("AppMessageBuyMKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy the TK version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageBuyTKVersion {
            get {
                return ResourceManager.GetString("AppMessageBuyTKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you use a cellular data connection charges may occur. WiFi is recommended.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageCellularChargeInfomation {
            get {
                return ResourceManager.GetString("AppMessageCellularChargeInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageConfirm {
            get {
                return ResourceManager.GetString("AppMessageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection has been lost.
        ///Are you sure you want to rescan your PC?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageDisconnectedFromPC {
            get {
                return ResourceManager.GetString("AppMessageDisconnectedFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press &apos;back&apos; one more time to exit WowPad.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageExit {
            get {
                return ResourceManager.GetString("AppMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageLoading {
            get {
                return ResourceManager.GetString("AppMessageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will not be able to connect to the PC.
        ///PC search again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageNotAbleConnectPC {
            get {
                return ResourceManager.GetString("AppMessageNotAbleConnectPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not be found host.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageNotFoundHost {
            get {
                return ResourceManager.GetString("AppMessageNotFoundHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageNotification {
            get {
                return ResourceManager.GetString("AppMessageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cellular data connection or WiFi network is required. WiFi settings would you like to do?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageRequiredDataNetwork {
            get {
                return ResourceManager.GetString("AppMessageRequiredDataNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WiFi settings are required. Do you want to set?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageRequiredWiFi {
            get {
                return ResourceManager.GetString("AppMessageRequiredWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy the full version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageTrialBuyFullversion {
            get {
                return ResourceManager.GetString("AppMessageTrialBuyFullversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buy the full version to use all the features.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageTrialBuyInfo {
            get {
                return ResourceManager.GetString("AppMessageTrialBuyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not available in the trial version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageTrialCannotuse {
            get {
                return ResourceManager.GetString("AppMessageTrialCannotuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC screen is displayed in black and white in the trial version. Displayed in color in the full version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageTrialTouchScreenColor {
            get {
                return ResourceManager.GetString("AppMessageTrialTouchScreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination host unreachable.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageUnreachableHost {
            get {
                return ResourceManager.GetString("AppMessageUnreachableHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} cellular data was used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppMessageUsage {
            get {
                return ResourceManager.GetString("AppMessageUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WowPad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have an Internet connection or page can not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpPageLoadFail {
            get {
                return ResourceManager.GetString("HelpPageLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to use WowPad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Histories과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HistoryListPageTitle {
            get {
                return ResourceManager.GetString("HistoryListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete access history of {0}?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HistoryPageRemoveItem {
            get {
                return ResourceManager.GetString("HistoryPageRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Because it is a network that is not accessible, you will not be able to use the WOL.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HistoryPageWOLCannotRequest {
            get {
                return ResourceManager.GetString("HistoryPageWOLCannotRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wake ON Lan to use the PC CMOS settings to be enabled. 
        ///For more information about set, 
        ///please contact PC manufacturer. 
        ///PC turn on request?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HistoryPageWOLConfirm {
            get {
                return ResourceManager.GetString("HistoryPageWOLConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power on request. 
        ///Please check with your PC.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HistoryPageWOLRequest {
            get {
                return ResourceManager.GetString("HistoryPageWOLRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageConnected {
            get {
                return ResourceManager.GetString("MainPageConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageDisconnected {
            get {
                return ResourceManager.GetString("MainPageDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back (only web browser)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageMouseBackClick {
            get {
                return ResourceManager.GetString("MainPageMouseBackClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward (only web browser)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageMouseForwardClick {
            get {
                return ResourceManager.GetString("MainPageMouseForwardClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click left button과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageMouseLeftClick {
            get {
                return ResourceManager.GetString("MainPageMouseLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move mouse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageMouseMovePointer {
            get {
                return ResourceManager.GetString("MainPageMouseMovePointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click right button과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainPageMouseRightClick {
            get {
                return ResourceManager.GetString("MainPageMouseRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerConnectPageAccessCode {
            get {
                return ResourceManager.GetString("ServerConnectPageAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerConnectPageConnecting {
            get {
                return ResourceManager.GetString("ServerConnectPageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerConnectPageConnectPC {
            get {
                return ResourceManager.GetString("ServerConnectPageConnectPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host name or IP address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerListPageHost {
            get {
                return ResourceManager.GetString("ServerListPageHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerListPagePort {
            get {
                return ResourceManager.GetString("ServerListPagePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerListPageSearching {
            get {
                return ResourceManager.GetString("ServerListPageSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerListPageSearchPC {
            get {
                return ResourceManager.GetString("ServerListPageSearchPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ServerListPageTitle {
            get {
                return ResourceManager.GetString("ServerListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use auto connect on start up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotConnectionAutoConnect {
            get {
                return ResourceManager.GetString("SettingsPagePivotConnectionAutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default port (default : 9000, range : 1024 ~ 65535)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotConnectionDefaultPort {
            get {
                return ResourceManager.GetString("SettingsPagePivotConnectionDefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device type on start up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotConnectionDeviceType {
            get {
                return ResourceManager.GetString("SettingsPagePivotConnectionDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotConnectionTitle {
            get {
                return ResourceManager.GetString("SettingsPagePivotConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data usage notification (If cellular data connection)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcDataUsage {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcDataUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   per 50MB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcDataUsageLevel1 {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcDataUsageLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   per 100MB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcDataUsageLevel2 {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcDataUsageLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   per 250MB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcDataUsageLevel3 {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcDataUsageLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   per 500MB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcDataUsageLevel4 {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcDataUsageLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default page of Search PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcDefaultPage {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use large keyboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcFullSizeKeyboard {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcFullSizeKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extras과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotEtcTitle {
            get {
                return ResourceManager.GetString("SettingsPagePivotEtcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background screen qualtiy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotTouchPadBackgroundQuality {
            get {
                return ResourceManager.GetString("SettingsPagePivotTouchPadBackgroundQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotTouchPadBackgroundQualityHigh {
            get {
                return ResourceManager.GetString("SettingsPagePivotTouchPadBackgroundQualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotTouchPadBackgroundQualityLow {
            get {
                return ResourceManager.GetString("SettingsPagePivotTouchPadBackgroundQualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotTouchPadBackgroundQualityMedium {
            get {
                return ResourceManager.GetString("SettingsPagePivotTouchPadBackgroundQualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use navigation button on browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotTouchPadNavigationButton {
            get {
                return ResourceManager.GetString("SettingsPagePivotTouchPadNavigationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TouchPad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPagePivotTouchPadTitle {
            get {
                return ResourceManager.GetString("SettingsPagePivotTouchPadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WowPad Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wake과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WOLPageRequestButton {
            get {
                return ResourceManager.GetString("WOLPageRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subnet Mask of {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WOLPageSubnetMask {
            get {
                return ResourceManager.GetString("WOLPageSubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wake on WAN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WOLPageTitle {
            get {
                return ResourceManager.GetString("WOLPageTitle", resourceCulture);
            }
        }
    }
}
